const Name_Or_Password_Cannot_Be_Empty = "NAME_OR_PASSWORD_CANNOT_BE_EMPTY";
const USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS";
const USER_DOES_NOT_EXIST = "USER_DOES_NOT_EXIST";
const WRONG_PASSWORD = "WRONG_PASSWORD";
const UNAUTHORIZED = "UNAUTHORIZED";
const NO_CONTROL_PERMISSIONS = "NO_CONTROL_PERMISSIONS";
module.exports = {
  Name_Or_Password_Cannot_Be_Empty,
  USERNAME_ALREADY_EXISTS,
  USER_DOES_NOT_EXIST,
  WRONG_PASSWORD,
  UNAUTHORIZED,
  NO_CONTROL_PERMISSIONS,
};
